// <auto-generated />
using api.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20171116205629_ChangeBeerStyleRatingModelTypes")]
    partial class ChangeBeerStyleRatingModelTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api.Domain.BeerStyleRatingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Abv");

                    b.Property<int>("Ale");

                    b.Property<int>("American");

                    b.Property<int>("Ibu");

                    b.Property<int>("Imperial");

                    b.Property<int>("Ipa");

                    b.Property<int>("Lager");

                    b.Property<int>("Pale");

                    b.Property<double>("Rating");

                    b.Property<int>("Stout");

                    b.Property<string>("User");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
