apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: null
    name: beertapped
  spec: {}
  status:
    phase: Active
- apiVersion: apps/v1beta2
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: beertapped-master
      version: master
    name: beertapped-master
    namespace: beertapped
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: beertapped-master
        version: master
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: beertapped-master
          version: master
        name: beertapped-master
      spec:
        containers:
        - image: eu.gcr.io/ptcs-docker-registry/beertapped:latest-master
          imagePullPolicy: Always
          name: beertapped-master
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: beertapped-master
      version: master
    name: beertapped-master
    namespace: beertapped
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
    selector:
      app: beertapped-master
      version: master
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: traefik
    creationTimestamp: null
    labels:
      traefik-type: public
    name: beertapped-master-ingress
    namespace: beertapped
  spec:
    rules:
    - host: beertapped-master.protacon.cloud
      http:
        paths:
        - backend:
            serviceName: beertapped-master
            servicePort: 80
    tls:
    - hosts:
      - beertapped-master.protacon.cloud
  status:
    loadBalancer: {}
kind: List
metadata: {}
